### ISSUE TITLE
CLI indexer breaks BV product grid

### ISSUE THREAD

**Issue by bobbrodie** [bazaarvoice/magento2-extension#38]
On Magento 2.2.5, when rebuilding the indexes via the CLI the grid on the Bazaarvoice Product Feed screen blanks all the fields except for Product ID, Store ID (this turns to 0), and Status (this turns to Enabled). Rebuilding again fixes the grid.

**Comment by jantzenw** [comment]
Hi bobbrodie,

Sorry for the (years) delay. I was going through old issues and pull requests and found this one. Quick background on this issue:

1. It is actually proper behavior that the indexer blank out most data during a reindex.
2. The indexer then populates the data within its allotted timeframe (typically 1 minute) and stops.
3. The indexer continues to automatically populate data (if the magento cron is running) over time, until the index is fully populated.
4. Running a manual CLI bv:index will blank out most data and restart the process.

Also, some time ago since the creation of this issue, the indexer logic was changed so that step #2 can proceed immediately after step #1 (as long as the indexer has not reached its time limit for the current cron run (typically within 1 minute). So it is less likely for users to see the indexed data during its blank state.

For these reasons, this issue is being closed. Thanks!
