### ISSUE TITLE
Magento 2.3 - Flat tables and Bazaarvoice

### ISSUE THREAD

**Issue by WinstonN** [bazaarvoice/magento2-extension#64]
Hi, 

With Magento 2.3 the use of flat tabes are discouraged, as can be seen here: https://docs.magento.com/m2/ce/user_guide/catalog/catalog-flat.html

Will you be making any changes to your module to support that?
Will your module support Magento 2.3.3? 

Winston

**Comment by WinstonN** [comment]
Hello, any update on this?

**Comment by WinstonN** [comment]
@jantzenw I really need some feedback here. Currently with flat tables disabled, we're getting this error

![image](https://user-images.githubusercontent.com/1143789/69580873-51846480-103a-11ea-8d3d-e394ff0fa3d7.png)

**Comment by jantzenw** [comment]
Hi @WinstonN, sorry for the delay. The module has a new catalog integration feature called Dynamic Catalog Collection (DCC), which is billed as a replacement for the Product XML File Feed catalog integration method. DCC is fully compatible with flat tables disabled (or enabled), and typically has a much easier setup and maintenance than the Product XML File Feed method. 

We highly suggest that you try out DCC instead and see if that satisfies your needs. Please see the latest documentation for information on DCC: https://knowledge.bazaarvoice.com/software/downloads/PartnerIntegrations/Magento_Extension/Magento_2/Conversations/

There is no plan for adding support for the Product XML File Feed to work with flat tables disabled at this time, because so far DCC has been an effective replacement. But we are interested to hear your feedback and will continue discussing this internally!

**Comment by mpchadwick** [comment]
The DCC approach can add a non-trivial amount of processing time on the PDP. In a configurable product with 200 child SKUs in an environment I've been playing it routinely adds ~0.5s to server response time. In New Relic in the worst case I can see that's frequently higher, sometimes as much as 1.5s. It also bloats the HTML payload (adds 94KB to the payload in the case of the configurable product in question) which will negatively impact frontend performance. It would be great if BazaarVoice continued to support the feed approach as it's less intrusive for users.

**Comment by jantzenw** [comment]
Hi @mpchadwick, thank you for the analysis. Since our last comment here, we have discussed and decided to continue supporting the product feed for the foreseeable future, and will be adding support for using the product feed with flat tables disabled. We will also look into ways to improve the performance of DCC, perhaps by moving it off of the initial page load. Thanks!

**Comment by jamestaylorSW** [comment]
Hi, I was just wondering if there was any update on the product feed support to disable flat tables?

**Comment by Abdallah-herri** [comment]
Hi, I was just wondering if there was any update on the product feed support to disable flat tables?

**Comment by jantzenw** [comment]
Hi,

v9.0.0 of the extension has been released today that supports the product xml feed with flat tables disabled. Please try that version and let us know if you encounter any issues.
